-- MySQL Script generated by MySQL Workbench
-- Sat Feb 10 08:46:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PurBeurreDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PurBeurreDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PurBeurreDB` DEFAULT CHARACTER SET utf8 ;
USE `PurBeurreDB` ;

-- -----------------------------------------------------
-- Table `PurBeurreDB`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PurBeurreDB`.`Categories` (
  `cat_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(75) NOT NULL,
  `cat_url` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PurBeurreDB`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PurBeurreDB`.`Product` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `pro_name` VARCHAR(75) NOT NULL,
  `pro_shop` VARCHAR(75) NULL,
  `pro_url` VARCHAR(150) NOT NULL,
  `pro_nutriscore` INT NOT NULL,
  `pro_cat_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`pro_id`),
  INDEX `fk_Product_Categories1_idx` (`pro_cat_id` ASC),
  UNIQUE INDEX `pro_name_UNIQUE` (`pro_name` ASC),
  CONSTRAINT `fk_Product_Categories1`
    FOREIGN KEY (`pro_cat_id`)
    REFERENCES `PurBeurreDB`.`Categories` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
